venus: Fix Invalid JSON
- Our bot reads this repo and responds to users,we were having problems because the json was incorrect.

Error: Parse error on line 26:
...xiaomi_venus"		}		{			"maintainer": "
---------------------^
Expecting 'EOF', '}', ',', ']', got '{'